output_folder: ./data/
######

op_times:
  - [0, 6]
  - [0, 6]
  - [0, 6]
  - [0, 6]
  - [0, 6]
  - [0, 6]
  - [0, 6]

######

cameras:
  - serial_number: 135522077052
    stream_configs:
      - type: depth
        format: z16
        resolution: x640_y480
        fps: fps_6
      - type: color
        format: rgb8
        resolution: x640_y480
        fps: fps_6

