output_folder: ./data/
######

op_times:
  - start_day: "Mon"
    start_time: "12:00"
    stop_day: "Mon"
    stop_time: "14:00"
  - start_day: "Mon"
    start_time: "13:00"
    stop_day: "Tue"
    stop_time: "14:00"

######

cameras:
  - serial_number: 939622075103
    stream_configs:
      - type: depth
        format: z16
        resolution: x640_y480
        fps: fps_6
      - type: color
        format: rgb8
        resolution: x640_y480
        fps: fps_6
