output_folder: ./data/

######################

op_time: [19, 21]

######

# op_times:
#   - [0, 6]
#   - [0, 6]
#   - [0, 6]
#   - [0, 6]
#   - [0, 6]
#   - [0, 6]
# - [0, 6]

######################

# camera: 135522077203

# stream_type: depth_n_color

######

# cameras:
#   - sn: 135522077052
#     name: Left camera
#     stream_type: depth
#     stream_config:
#       depth:
#         width: 640
#         height: 480
#         fps: 30
#         format: z16
#   - sn: 135522071130
#     name: Right camera
#     stream_type: depth
#     stream_config:
#       depth:
#         width: 640
#         height: 480
#         fps: 30
#         format: z16

