output_folder: ./
######

op_times:
  - start_day: "Mon"
    start_time: "12:00"
    stop_day: "Mon"
    stop_time: "14:00"

  - start_day: "Tue"
    start_time: "12:00"
    stop_day: "Tue"
    stop_time: "14:00"

  - start_day: "Wed"
    start_time: "12:00"
    stop_day: "Wed"
    stop_time: "14:00"

  - start_day: "Thu"
    start_time: "12:00"
    stop_day: "Thu"
    stop_time: "14:00"

  - start_day: "Fri"
    start_time: "12:00"
    stop_day: "Fri"
    stop_time: "14:00"

######

cameras:
  - serial_number:
    stream_configs:
      - type: depth
        format: z16
        resolution: x640_y480
        fps: fps_15
      - type: color
        format: rgb8
        resolution: x640_y480
        fps: fps_15
    align_to: color
