mode: aquire

output_folder: ./

op_times:
  - [0, 24]
  - [0, 24]
  - [0, 24]
  - [0, 24]
  - [0, 24]
  - [0, 24]
  - [0, 24]

# Define the input source for the data to be acquired
cameras:
  - sn: 135522077203
    name: Left camera
    stream_type:
    stream_config:
      depth:
        width: 640
        height: 480
        fps: 30
        format: z16
      color:
        width: 640
        height: 480
        fps: 30
        format: rgb8
