mode: aquire

output_folder: ./

op_times:
  - [0, 0, 24]
  - [1, 0, 24]
  - [2, 0, 24]
  - [3, 0, 24]
  - [4, 0, 24]
  - [5, 0, 24]
  - [6, 0, 0]

# Define the input source for the data to be acquired
cameras:
  - sn: 1355220772030
    name: Left camera
    stream_type: depth
    stream_config:
      depth:
        width: 640
        height: 480
        fps: 30
        format: z16
      color:
        width: 640
        height: 480
        fps: 30
        format: z16
