mode: aquire

output_folder: ./

operation_time:
  -

# Define the input source for the data to be acquired
cameras:
  - sn: 1355220772030
    name: Left camera
    stream_type: depth
    stream_config:
      depth:
        width: 640
        height: 480
        fps: 30
        format: z16
      color:
        width: 640
        height: 480
        fps: 30
        format: z16
